### ISSUE TITLE
Iryna Kazlova / Specify solution template

### ISSUE THREAD

**Issue by parys** [parys/internship#1]
Create branch for this feature.
Create solution template.
Create folders and projects.
Commit it to github.
Create PR to main branch.

**Comment by 4500zenja1** [comment]
And there we can close this issue too, because of merged PR #3.

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iryna Kazlova / Specify solution template #1](https://trello.com/c/Q5EOYxtd/104-iryna-kazlova-specify-solution-template-1)
