### ISSUE TITLE
Evgenoy Kowpak/Correct some mistake

### ISSUE THREAD

**Issue by Evgenij-Kovpak** [parys/internship#11]
Correct some mistake in Gramma class

**Comment by Evgenij-Kovpak** [comment]
Correct some mistake in Gramma class

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Evgenoy Kowpak/Correct some mistake #11](https://trello.com/c/KYndUjk0/99-evgenoy-kowpak-correct-some-mistake-11)
