### ISSUE TITLE
Andrey Rogov / Change Essay and Speaking type with Topic in Test enetity

### ISSUE THREAD

**Issue by andreyrogov8** [parys/internship#15]

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Andrey Rogov / Change Essay and Speaking type with Topic in Test enetity #15](https://trello.com/c/EZcdvtjl/98-andrey-rogov-change-essay-and-speaking-type-with-topic-in-test-enetity-15)
