### ISSUE TITLE
Evgeny Kurmysa/Erase extra Id properties

### ISSUE THREAD

**Issue by andreyrogov8** [parys/internship#34]

**Comment by 4500zenja1** [comment]
#35 is pulled, the issue is closed now.

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Evgeny Kurmysa/Erase extra Id properties #34](https://trello.com/c/zPilkbq6/89-evgeny-kurmysa-erase-extra-id-properties-34)
