### ISSUE TITLE
Veronika Olshevska/ Add Deleted property for Topic and Questiones entities

### ISSUE THREAD

**Issue by Oniksiyaa** [parys/internship#47]

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Veronika Olshevska/ Add Deleted property for Topic and Questiones entities #47  Closed](https://trello.com/c/DSVKQqTP/87-veronika-olshevska-add-deleted-property-for-topic-and-questiones-entities-47-closed)
