### ISSUE TITLE
Iryna Kazlova / Implement authentication and authorization

### ISSUE THREAD

**Issue by rinchan603** [parys/internship#5]
Authenticate a user by email and password.
Create and send to user an access token (JWT).
Add 4 roles to the app: Admin, User, HR, Coach.
Seed default set of users to DB with roles.

**Comment by 4500zenja1** [comment]
Because of merged PR #13, this issue can be closed right now.

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iryna Kazlova / Implement authentication and authorization #5](https://trello.com/c/5XqULrjl/102-iryna-kazlova-implement-authentication-and-authorization-5)
