### ISSUE TITLE
Iryna Kazlova / Implement Update Command for TestQuestion

### ISSUE THREAD

**Issue by rinchan603** [parys/internship#54]

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iryna Kazlova / Implement Update Command for TestQuestion #54](https://trello.com/c/5FxzFEW1/85-iryna-kazlova-implement-update-command-for-testquestion-54)

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iryna Kazlova / Implement Update Command for TestQuestion #54](https://trello.com/c/7Yrc8bvj/86-iryna-kazlova-implement-update-command-for-testquestion-54)
