### ISSUE TITLE
Iryna Kazlova / Implement pagination

### ISSUE THREAD

**Issue by rinchan603** [parys/internship#58]

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement file handler #68](https://trello.com/c/ENNkQqEH/67-implement-file-handler-68)

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Iryna Kazlova / Implement pagination #58](https://trello.com/c/LLEkkoMB/82-iryna-kazlova-implement-pagination-58)
