### ISSUE TITLE
Istomin Roman/Impliment Audition, Essay, Speaking entities

### ISSUE THREAD

**Issue by ristomin** [parys/internship#7]

**Comment by 4500zenja1** [comment]
#9

**Comment by 4500zenja1** [comment]
#14 is merged, I can close this issue now.

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Istomin Roman/Impliment Audition, Essay, Speaking entities #7](https://trello.com/c/s93p4acQ/101-istomin-roman-impliment-audition-essay-speaking-entities-7)
