### ISSUE TITLE
Implement UserAnswers, Questions and Answers

### ISSUE THREAD

**Issue by Evgenij-Kovpak** [parys/internship#8]
Create models

**Comment by 4500zenja1** [comment]
The issue was completed with PR #10, therefore this issue is closed now.

**Comment by IrynaFiadchuk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement UserAnswers, Questions and Answers #8](https://trello.com/c/EBjaWRtc/100-implement-useranswers-questions-and-answers-8)
